# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: HighCharts Build 
trigger:
  - ReleaseBuild

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      npm install
    displayName: "npm install"
    
  - script: |
      npm run build
    displayName: "npm run build"

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: dist  
      pathtoPublish: "$(Build.SourcesDirectory)/dist"
      publishLocation: FilePath
      TargetPath: '\\nbs-a5-001\Drops\HighChart\$(Build.BuildNumber)'
    displayName: "Publish Artifact: HighChart"
