# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda env create --quiet --file environment.yml --name anacondaEnvironment
    displayName: Create Anaconda environment

  - bash: |
      source activate anacondaEnvironment
      conda install --yes --quiet --name anacondaEnvironment scipy
    displayName: Install Anaconda packages

  - bash: |
      source activate anacondaEnvironment
      conda npm run update-all-data
    displayName: conda update data

  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(Build.SourcesDirectory)/dist"
      contents: "**"
      targetFolder: $(Build.ArtifactStagingDirectory)/dist
    displayName: "Copy /dist directory"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)/dist"
      artifactName: dist
    displayName: "Publish dist artifact"
