# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: HighCharts Build 
trigger:
  - ReleaseBuild

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      npm install
    displayName: "npm install"
    
  - script: |
      npm run dev
    displayName: "npm run dev"
    
  - script: |
      npm run build
    displayName: "npm run build"
    
  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(Build.SourcesDirectory)/dist"
      contents: "**"
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: "Copy /dist directory"

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: dist  
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      publishLocation: 'pipeline'
    displayName: "Publish dist artifact"
